import {Player} from './audio.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const roles=['Bass','Keys','Lead','Drums'], styles=['Pocket','Restless','Spacious'],colors=['#d5fa76','#a5b5ff','#f3a978','#72d3b3'];
const bios=[['The anchor. Measured root notes and a steady pulse give the band somewhere to land.','Short notes and fifths that push the groove forward. A little more motion beneath the harmony.','Long roots, unhurried phrases. Leaves room for the others to move.'],['Measured chord cues with a clear pulse. Sets up a conversation for bass and lead.','Quick chord stabs and short releases. Makes space by keeping things moving.','Held chords and breathing room. A broad harmonic canvas for the band.'],['Measured replies built around thirds. A melodic partner that takes its time.','Quick fifths and third-note turns. The most talkative voice in the room.','Held root-note replies. Finds a melody in fewer, longer gestures.'],['An even eighth-note pulse. Keeps the conversation grounded.','Busy sixteenth-note hats and extra movement. Brings nervous energy to the room.','Open quarter-note hats. A lighter touch with more space between hits.']];
const info=[['First rehearsal','Original output','The original downloaded checkpoint, before the adaptive training runs.','Listen for the starting balance of notes, silence, and sustained tones. These are eight-bar free performances with the same lineup across stages.'],['Holding a note','Run 01 · Duration','A shared note-transition model learns when to hold and release notes.','Duration improved: pocket bass notes settled near two steps, while spacious keys held for about five. Listening to peers still had little measurable effect.'],['Learning to listen','Run 02 · Conversation','New practice material teaches explicit keyboard cues and musical replies.','Changing the practice data alone was not enough. Generated bass and lead each answered only 2 of 48 cue positions correctly in the response test.'],['Hearing the pitch','Run 03 · Pitch context','A pitch-aware listener connects the other players’ notes across time.','Generated bass replies reached 42 of 48 correct pitches, and lead reached 18 of 48, with the keyboard fixed as a cue.'],['Learning to answer','Run 04 · Pitch objective','A focused pitch objective rewards the right musical answer.','On three fresh keyboard-led prompts, bass answered 48 of 48 cue pitches correctly and lead 31 of 48. These small synthetic tests measure response accuracy, not overall musical quality.']];
let mode='stages',stage=4,choices=[0,2,1,0],stages=[],catalog={},current,ready=false,response=false;
const player=new Player(()=>renderPlayback());
$('#stages').innerHTML=info.map((x,i)=>`<button class="stage ${i===4?'active':''}" data-stage="${i}" aria-pressed="${i===4}"><small>${String(i).padStart(2,'0')} / ${i===0?'BASELINE':'1,000 UPDATES'}</small><strong>${x[0]}</strong><span>${x[1]}</span></button>`).join('');
$('#musicians').innerHTML=roles.map((r,i)=>`<article class="musician" style="--track:${colors[i]}"><span class="role">0${i+1} / ${r}</span><label><span class="sr-only" hidden>${r} musician</span><select aria-label="${r} musician" data-role="${i}">${styles.map((s,j)=>`<option value="${j}" ${j===choices[i]?'selected':''}>${s}</option>`).join('')}</select></label><p id="bio-${i}">${bios[i][choices[i]]}</p><small>VIRTUAL ${r.toUpperCase()} PLAYER</small></article>`).join('');
$('#mixer').innerHTML=roles.map((r,i)=>`<div class="channel" style="--track:${colors[i]}"><div class="channel-name"><strong>${r}</strong><span id="player-${i}"></span></div><p id="notes-${i}">— notes</p><div class="volume-label"><label for="vol-${i}">Volume</label><output id="value-${i}">${Math.round(player.volumes[i]*100)}%</output></div><input id="vol-${i}" type="range" min="0" max="100" value="${player.volumes[i]*100}" data-volume="${i}"><div class="channel-actions"><button data-mute="${i}" aria-label="Mute ${r}" aria-pressed="false">Mute</button><button data-solo="${i}" aria-label="Solo ${r}" aria-pressed="false">Solo</button></div></div>`).join('');
function setMode(value){mode=value;response=false;$$('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode))});$('#stages-panel').hidden=mode!=='stages';$('#band-panel').hidden=mode!=='band';loadTake();}
function loadTake(){if(!ready)return;const key=choices.join('');current=response?responseTake:mode==='stages'?stages[stage]:catalog[key];if(!current){$('#play-status').textContent='This rehearsal is still being prepared.';$('#play').disabled=true;return}player.setTake(current);$('#play').disabled=false;
$('#take-label').textContent=response?'KEYBOARD-LED RESPONSE TEST':mode==='stages'?`TRAINING STAGE ${String(stage).padStart(2,'0')}`:'YOUR SUPERGROUP / FOUR-BAR REHEARSAL';$('#take-title').textContent=response?'A cue. An answer.':mode==='stages'?info[stage][0]:choices.every(x=>x===choices[0])?`The ${styles[choices[0]]} Quartet`:`${styles[choices[0]]} foundations, ${styles[choices[2]].toLowerCase()} ideas`;
$('#take-description').textContent=response?'Run 04, fresh held-out keyboard prompt. Keys are fixed; the other players generate their replies.':mode==='stages'?info[stage][2]:'A saved performance generated jointly by this lineup with the final checkpoint. Change a musician to hear a different rehearsal.';
$('#insight').textContent=mode==='stages'?info[stage][3]:'These four-bar rehearsals use the final trained checkpoint, two listening rounds, and all 81 possible lineups. Each has its own sampled notes, so differences reflect both identity and sampling. Free performances can be sparse; the keyboard-led test demonstrates interaction more clearly.';
$('#download').href=`assets/${response?'response':mode==='stages'?`stage-${stage}`:`band-${key}`}.mid`;$('#duration').textContent=format(player.duration);$('.bar-labels').innerHTML=Array.from({length:current.steps/16},(_,i)=>`<span>${String(i+1).padStart(2,'0')}</span>`).join('');roles.forEach((r,i)=>{$(`#player-${i}`).textContent=styles[current.lineup[i]%3];$(`#notes-${i}`).textContent=`${current.tracks[i].length} notes · ${current.bpm} BPM`});renderPlayback();draw();}
let responseTake;
function format(t){return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
function renderPlayback(){const t=player.current();$('#play').textContent=player.playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',player.playing?'Pause performance':'Play performance');$('#play-status').textContent=player.playing?'Playing together':ready?'Ready when you are':'Loading performances…';$('#time').textContent=format(t||0);$('#seek').value=player.duration?t/player.duration*1000:0;$('#cursor').style.left=`${player.duration?t/player.duration*100:0}%`;}
function draw(){if(!current)return;const c=$('#roll'),w=c.clientWidth,h=c.clientHeight,dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);for(let s=0;s<=current.steps;s+=4){ctx.strokeStyle=s%16===0?'#354035':'#202a22';ctx.beginPath();ctx.moveTo(s/current.steps*w,0);ctx.lineTo(s/current.steps*w,h);ctx.stroke()}current.tracks.forEach((notes,r)=>{const y=r*h/4;ctx.strokeStyle='#354035';ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();ctx.fillStyle=colors[r];ctx.globalAlpha=player.muted[r]||(player.solo.some(Boolean)&&!player.solo[r])?.15:.85;const pitches=notes.map(n=>n[2]),lo=Math.min(...pitches),hi=Math.max(...pitches);for(const [s,d,p,v] of notes){const py=y+8+(hi-p)/Math.max(1,hi-lo)*(h/4-18);ctx.fillRect(s/current.steps*w,py,Math.max(2,d/current.steps*w-1),4)}ctx.globalAlpha=1});}
function updateMix(){player.updateMix();$$('[data-mute]').forEach(b=>b.setAttribute('aria-pressed',player.muted[+b.dataset.mute]));$$('[data-solo]').forEach(b=>b.setAttribute('aria-pressed',player.solo[+b.dataset.solo]));draw();}
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-stage]').forEach(b=>b.onclick=()=>{stage=+b.dataset.stage;response=false;$$('[data-stage]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});loadTake()});
function setLineup(next){if(!Array.isArray(next)||next.length!==4||next.some(x=>!Number.isInteger(x)||x<0||x>2))throw Error('Choose four style indices between 0 and 2.');choices=[...next];$$('[data-role]').forEach((s,i)=>{s.value=choices[i];$(`#bio-${i}`).textContent=bios[i][choices[i]]});setMode('band');}
$$('[data-role]').forEach(s=>s.onchange=()=>{const next=[...choices];next[+s.dataset.role]=+s.value;setLineup(next)});$('#shuffle').onclick=()=>setLineup(choices.map(()=>Math.floor(Math.random()*3)));
$('#play').disabled=true;$('#play').onclick=async()=>{try{if(player.playing)player.pause();else await player.play();renderPlayback()}catch(e){$('#play-status').textContent='Audio could not start. Press play to try again.';console.error(e)}};$('#restart').onclick=async()=>{await player.seek(0);renderPlayback()};$('#seek').oninput=async e=>{await player.seek(+e.target.value/1000*player.duration);renderPlayback()};$('#loop').onclick=()=>{$('#loop').setAttribute('aria-pressed',player.loop=!player.loop)};
$$('[data-volume]').forEach(s=>s.oninput=()=>{let r=+s.dataset.volume;player.volumes[r]=+s.value/100;$(`#value-${r}`).value=s.value+'%';updateMix()});$$('[data-mute]').forEach(b=>b.onclick=()=>{let r=+b.dataset.mute;player.muted[r]=!player.muted[r];updateMix()});$$('[data-solo]').forEach(b=>b.onclick=()=>{let r=+b.dataset.solo;player.solo[r]=!player.solo[r];updateMix()});$('#master').oninput=e=>{player.masterVolume=+e.target.value/100;$('#master-value').value=e.target.value+'%';updateMix()};$('#reset').onclick=()=>{player.volumes=[.8,.7,.65,.65];player.muted.fill(false);player.solo.fill(false);player.masterVolume=.75;$('#master').value=75;$('#master-value').value='75%';$$('[data-volume]').forEach((s,i)=>{s.value=player.volumes[i]*100;$(`#value-${i}`).value=s.value+'%'});updateMix()};$('#response').onclick=()=>{response=true;loadTake()};
window.addEventListener('resize',draw);function frame(){if(player.playing)renderPlayback();requestAnimationFrame(frame)}frame();
try{[stages,catalog,responseTake]=await Promise.all(['stages','catalog','response'].map(async f=>{const r=await fetch(`assets/${f}.json`);if(!r.ok)throw Error(f);return r.json()}));ready=true;loadTake()}catch(e){$('#play-status').textContent='Could not load performances. Reload to try again.';console.error(e)}
if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'configure_supergroup',description:'Choose the four virtual musician styles and load their saved joint rehearsal. Does not start audio.',inputSchema:{type:'object',properties:{styles:{type:'array',items:{type:'integer',minimum:0,maximum:2},minItems:4,maxItems:4}},required:['styles'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!ready)throw Error('Performances are still loading');setLineup(input.styles);return {lineup:choices.map((s,i)=>`${styles[s]} ${roles[i]}`),loaded:!!current}}})}catch(e){console.warn('WebMCP registration unavailable',e)}}
