// All tracks share one audio clock. Gains are downstream of scheduled voices.
export class Player {
  constructor(onEnd){this.onEnd=onEnd;this.position=0;this.playing=false;this.loop=false;this.volumes=[.8,.7,.65,.65];this.muted=[false,false,false,false];this.solo=[false,false,false,false];this.masterVolume=.75;this.voices=[];}
  async init(){if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.connect(this.ctx.destination);this.channels=this.volumes.map(()=>{let g=this.ctx.createGain();g.connect(this.master);return g});this.updateMix();}await this.ctx.resume();}
  setTake(take){this.pause();this.take=take;this.duration=take.steps*60/take.bpm/4;this.position=0;}
  current(){return this.playing?Math.max(0,Math.min(this.duration,this.ctx.currentTime-this.started)):this.position;}
  updateMix(){if(!this.ctx)return;const any=this.solo.some(Boolean);this.channels.forEach((g,i)=>g.gain.setTargetAtTime(this.muted[i]||(any&&!this.solo[i])?0:this.volumes[i],this.ctx.currentTime,.012));this.master.gain.setTargetAtTime(this.masterVolume*.55,this.ctx.currentTime,.012);}
  pause(){if(this.playing)this.position=this.current();this.playing=false;clearTimeout(this.timer);for(const v of this.voices){try{v.stop()}catch{}}this.voices=[];}
  async play(){if(!this.take)return;await this.init();if(this.playing)return;if(this.position>=this.duration-.01)this.position=0;this.started=this.ctx.currentTime-this.position+.035;this.playing=true;const step=60/this.take.bpm/4;this.take.tracks.forEach((notes,r)=>notes.forEach(([s,d,p,v])=>{const start=s*step,end=start+d*step;if(end<=this.position)return;this.voice(r,p,v,Math.max(this.ctx.currentTime+.035,this.started+start),Math.max(.03,end-Math.max(start,this.position)));}));this.timer=setTimeout(()=>{this.pause();this.position=0;if(this.loop)this.play();this.onEnd?.()},(this.duration-this.position+.06)*1000);}
  async seek(seconds){const resume=this.playing;this.pause();this.position=Math.max(0,Math.min(this.duration,seconds));if(resume)await this.play();}
  voice(role,pitch,velocity,at,duration){const c=this.ctx,g=c.createGain(),amp=(velocity/127)*[.23,.12,.14,.23][role];g.connect(this.channels[role]);let source;
    if(role===3&&pitch!==35&&pitch!==36){const length=Math.ceil(c.sampleRate*(pitch===42||pitch===44?.07:.16));const buffer=c.createBuffer(1,length,c.sampleRate),data=buffer.getChannelData(0);let seed=pitch*7919+velocity;for(let i=0;i<length;i++){seed=(seed*16807)%2147483647;data[i]=(seed/1073741824-1)*Math.exp(-i/length*5)}source=c.createBufferSource();source.buffer=buffer;const filter=c.createBiquadFilter();filter.type='highpass';filter.frequency.value=pitch===42||pitch===44?6500:1400;source.connect(filter);filter.connect(g);duration=length/c.sampleRate;
    }else{source=c.createOscillator();source.type=role===0?'triangle':role===1?'sine':role===2?'triangle':'sine';source.frequency.setValueAtTime(role===3?140:440*Math.pow(2,(pitch-69)/12),at);if(role===3){source.frequency.exponentialRampToValueAtTime(42,at+.13);duration=.18}source.connect(g);}
    g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(amp,at+.008);g.gain.exponentialRampToValueAtTime(Math.max(.001,amp*.55),at+Math.max(.01,duration*.6));g.gain.linearRampToValueAtTime(0,at+duration+.045);source.start(at);source.stop(at+duration+.06);source.onended=()=>{g.disconnect();source.disconnect();const i=this.voices.indexOf(source);if(i!==-1)this.voices.splice(i,1)};this.voices.push(source);
  }
}
